network:
  - interface: wan0
    network: tcp
    address: 8.8.8.8:53
  #    timeout: 100ms # default
  #    timer: 30s # default
  - interface: lan
    network: tcp
    timeout: 5ms
    timer: 1s
  - interface: tun0
    network: udp
    timeout: 120ms
    timer: 5s
  - interface: tun1
    network: udp
    timeout: 70ms
    timer: 5s
